import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAMIRO
 */
public class MunicipiosUF extends javax.swing.JFrame {
    ConexaoBD con = new ConexaoBD();
    String UF;
    List<MunicipioBean> municipios;
    

    DefaultTableModel tmMunicipiosUF = new DefaultTableModel(null, new String[]{"UF", "MUNICIPIO"}) {

        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };

    ListSelectionModel lsmMunicipiosUF;

    /**
     * Creates new form MunicipiosUF
     */
    public MunicipiosUF() {
        initComponents();
        preencheCBUF();
    }
    
    public void preencheCBUF(){
        try{
            con.conecta();
            String sql = "SELECT DISTINCT SIGLA_UF FROM MunicipiosUF ORDER BY SIGLA_UF";
            con.executeSQL(sql);
            cbUF.addItem("Selecione ...");
            while(con.rs.next()){
                cbUF.addItem(con.rs.getString("SIGLA_UF"));
            }
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            con.desconecta();
        }
    }
    
    public void preencheCBMunicipio(){
        municipios = new ArrayList();
        try{
            con.conecta();
            String sql = "SELECT * FROM MunicipiosUF where SIGLA_UF='"+UF+"'";
            con.executeSQL(sql);
            MunicipioBean mb;
            cbMunicipio.addItem("Selecione ...");
            while(con.rs.next()){
                cbMunicipio.addItem(con.rs.getString("MUNICIPIOS"));
                mb = new MunicipioBean();
                mb.setCoduf(con.rs.getInt("COD_UF"));
		mb.setSiglauf(con.rs.getString("SIGLA_UF"));
		mb.setCodmunic(con.rs.getInt("COD_MUNIC"));
		mb.setMunicipio(con.rs.getString("MUNICIPIOS"));
                municipios.add(mb);
            }
            preencheTBMunicipio(municipios);
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            con.desconecta();
        }
    }
    
    public void preencheTBMunicipio(List<MunicipioBean> municipios){
        tbMunicipios.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbMunicipios.getColumnModel().getColumn(1).setPreferredWidth(165);

        while (tmMunicipiosUF.getRowCount() > 0) {
            tmMunicipiosUF.removeRow(0);
        }

        if (municipios.size() == 0) {
            //JOptionPane.showMessageDialog(this, "Nenhum Município Encontrado!");
        } else {
        }
        String[] campos = new String[]{null, null};
        for (int i = 0; i < municipios.size(); i++) {

            tmMunicipiosUF.addRow(campos);
            tmMunicipiosUF.setValueAt(municipios.get(i).getSiglauf(), i, 0);
            tmMunicipiosUF.setValueAt(municipios.get(i).getMunicipio(), i, 1);
        }        
        
    }
    
    public void mostraDadosTF(JTable tb){
        if (tb.getSelectedRow() != -1) {
            tfCodUF.setText("" + municipios.get(tb.getSelectedRow()).getCoduf());
            tfUF.setText(municipios.get(tb.getSelectedRow()).getSiglauf());
	    tfCodMunicipio.setText("" + municipios.get(tb.getSelectedRow()).getCodmunic());
	    tfMunicipio.setText(municipios.get(tb.getSelectedRow()).getMunicipio());
	    
        }
    }
    
    public void limparCampos(){
        tfCodUF.setText("");
        tfUF.setText("");
        tfCodMunicipio.setText("");
        tfMunicipio.setText("");
        tmMunicipiosUF.setNumRows(0);
        cbUF.setSelectedItem("Selecione ...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMunicipios = new javax.swing.JTable();
        cbUF = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMunicipio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfCodUF = new javax.swing.JTextField();
        tfUF = new javax.swing.JTextField();
        tfCodMunicipio = new javax.swing.JTextField();
        tfMunicipio = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Municípios por UF by rolipam Informática");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        tbMunicipios.setModel(tmMunicipiosUF);
        tbMunicipios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
        lsmMunicipiosUF = tbMunicipios.getSelectionModel();  
        lsmMunicipiosUF.addListSelectionListener(new ListSelectionListener() {          
            public void valueChanged(ListSelectionEvent e){          
                if(!e.getValueIsAdjusting()){          
                    mostraDadosTF(tbMunicipios);  
                }  
            }  
        });
        jScrollPane1.setViewportView(tbMunicipios);

        cbUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUFActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado:");

        jLabel2.setText("Município:");

        cbMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMunicipioActionPerformed(evt);
            }
        });

        jLabel3.setText("Código da UF:");

        jLabel4.setText("UF:");

        jLabel5.setText("Código do Município:");

        jLabel6.setText("Município:");

        tfCodUF.setEditable(false);
        tfCodUF.setFocusable(false);

        tfUF.setEditable(false);
        tfUF.setFocusable(false);

        tfCodMunicipio.setEditable(false);
        tfCodMunicipio.setFocusable(false);

        tfMunicipio.setEditable(false);
        tfMunicipio.setFocusable(false);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jMenu1.setMnemonic('A');
        jMenu1.setText("Arquivo");

        menuSair.setMnemonic('S');
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfCodUF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(tfUF, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btLimpar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfCodMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCodUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCodMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMunicipioActionPerformed

    private void cbUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUFActionPerformed
        if(!cbUF.getSelectedItem().equals("Selecione ...")){
            UF = String.valueOf(cbUF.getSelectedItem());
            cbMunicipio.removeAllItems();
            preencheCBMunicipio();
        }else if(cbUF.getSelectedItem().equals("Selecione ...")){
            cbMunicipio.removeAllItems();
            tmMunicipiosUF.setNumRows(0);
        }
    }//GEN-LAST:event_cbUFActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MunicipiosUF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MunicipiosUF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MunicipiosUF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MunicipiosUF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MunicipiosUF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JComboBox<String> cbMunicipio;
    private javax.swing.JComboBox<String> cbUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JTable tbMunicipios;
    private javax.swing.JTextField tfCodMunicipio;
    private javax.swing.JTextField tfCodUF;
    private javax.swing.JTextField tfMunicipio;
    private javax.swing.JTextField tfUF;
    // End of variables declaration//GEN-END:variables
}
